#!/usr/bin/env bash
#
# Start local monitoring stack (MongoDB + hcms watcher).

set -o errexit
set -o pipefail
set -o nounset

# shellcheck disable=SC1091
source utils.sh

check_command docker

fancy_echo "Starting local monitoring stack"
docker compose --file compose.yml up --detach --remove-orphans
docker compose --file compose.yml watch --no-up &
