name: Functional testing

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null
  workflow_dispatch: # Enables manual trigger

env:
  MODEL_API_KEY: dummy-key
  MODEL_ENDPOINT: dummy-endpoint
  BATCH_MODEL_NAME: dummy-batch-model

jobs:
  pytest:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install poetry
        run: |
          python -m pip install poetry==2.1.2

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v4
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-3.13-${{ hashFiles('**/poetry.lock') }}-self-hosted

      - name: Install Python package
        run: |
          ./script/install

      - name: Run pytest test suite
        run: |
          ./script/test

      - name: Test Summary
        uses: test-summary/action@v2.4
        with:
          paths: ".test_report.xml"
          show: "fail"
        if: always()
